### ISSUE TITLE
two issues i've picked up

### ISSUE THREAD

**Issue by networkop** [darkiesan/CV-EOS-Conversion#4]
Hey Patrik,
thanks for your script. Just updated 100s of configlets in a few minutes, so thanks for writing it. I've stumbled across a couple of issues with regex matching:
1. Some configlets were already updated and got converted twice. For example
`system control-plane` became `system system control-plane`

2. BGP peer-group in `bgp listen range` command did not get convereted. I'm not sure if it's a bug with CLI agent on 4.22.1F, but if it's not, the following command still requires hyphen in peer group
`bgp listen range 10.120.0.0/16 peer-group`

**Comment by darkiesan** [comment]
Hello,
Sorry for such a late reply.
BGP listen ranged was fixed now.
I will see what we can do about system control-plane.

Thx
Patrik

**Comment by darkiesan** [comment]
So the script is not meant to be executed more than once.
We will not do anything about that right now.
Might look into this if needed later, but its gonna be really hard to have a statement that before a regex checks that the statement have been converted, i.e. follow the new standard.
